name: Finding Collatz Conjectural Counterexamples
on:
  schedule:
   - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      numFiles:
        description: 'Number of calculations'
        required: false
        default: '5000000'
        type: string

run-name: Finding Collatz Conjectural Counterexamples ( ${{ github.event.inputs.numFiles || '5000000' }} )

concurrency:
  group: my-workflow-group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '23.x'
      # - name: Run script
      #   run: node script.js ${{ github.event.inputs.numFiles || '1000000' }}
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - name: Run Find-Collatz-Conjecture-Counterexamples.jl
        run: julia Find-Collatz-Conjecture-Counterexamples.jl ${{ github.event.inputs.numFiles || '5000000' }}
